name = "Jsdetox2"
license = "MIT"
licenselink = "https://github.com/fredrikloch/jsdetox2/blob/master/LICENSE"
description = " "
homepage = "https://github.com/fredrikloch/jsdetox2/"
tags = ["blog", "minimal", "ghost", "white"]
features = ["blog", "pagination", "rss"]
min_version = "0.41.0"

[author]
  name = "Fredrik Loch"
  homepage = "https://fredrikloch.me"

# If porting an existing theme
[original]
  name = "Jordan Bowman"
  homepage = "http://www.jrdnbwmn.com"
  repo = "https://github.com/jrdnbwmn/detox"